---
title: "FASTQ Quality Control"
author: "Sam Buckberry"
date: "23/10/2021"
output: html_document
---
Load R libraries 
```{r, message=FALSE}
library(stringr)
library(magrittr)
library(Rfastp)
library(DT)
library(ggplot2)
#library(cowplot)
```

### FASTQ quality control and filtering


Example (no need to run)
```{r, cache=TRUE, eval=FALSE}
read1 <- "fastq/1001-Effector_CD4pos_T-S_chr22_R1.fastq.gz"
read2 <- "fastq/1001-Effector_CD4pos_T-S_chr22_R2.fastq.gz"

out_prefix <- str_replace(string = read1,
                          pattern = "_R1.fastq.gz",
                          replacement = "_filt_fastp")

fastp_json_report <- rfastp(read1 = read1, read2 = read2, 
                            outputFastq = out_prefix,
                            adapterTrimming = TRUE,
                            cutLowQualTail = TRUE,
                            cutLowQualFront = TRUE,
                            thread = 1)
```

Write a function to process all the samples. 
```{r, cache=TRUE, message=FALSE}
r1_list <- list.files(path = "fastq/",
                      pattern = "chr22_R1.fastq.gz",
                      full.names = TRUE)

r2_list <- list.files(path = "fastq/",
                      pattern = "chr22_R2.fastq.gz",
                      full.names = TRUE)

fq_df <- data.frame(r1 = r1_list, r2 = r2_list,
                    prefix = str_replace(r1_list,
                                        pattern = "_chr22_R1.fastq.gz",
                                        replacement = "_filt_fastp"))

multi_fastp <- function(x){
    
    fastp_json_report <- rfastp(read1 = fq_df$r1[x],
                                read2 = fq_df$r2[x], 
                            outputFastq = fq_df$prefix[x],
                            adapterTrimming = TRUE,
                            cutLowQualTail = TRUE,
                            cutLowQualFront = TRUE,
                            thread = 2)
    return(fastp_json_report)
}

report_list <- lapply(1:nrow(fq_df), multi_fastp)

```

Generate a table of statistics
```{r}

# Short function to extract summary data from fastp
get_report <- function(x){unlist(report_list[[x]]$summary)}

# Make a table of the report data.
# Some re-formatting of the numbers is required. 
report_table <- lapply(1:length(report_list), get_report) %>%
    do.call(cbind, .) %>% 
    format(scientific=FALSE,
           digits = 2,
           drop0trailing = TRUE)

report_table <- data.frame(report_table)
colnames(report_table) <- fq_df$prefix

datatable(data = report_table)
```

Make some plots of the statistics
```{r}
cp_list <- lapply(X = 1:length(report_list),
                  FUN = function(x){curvePlot(report_list[[x]]) + ggtitle(fq_df$prefix[x])})
cp_list
````



